[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable IR compilation to handle stack too deep errors
via_ir = true
optimizer = true
optimizer_runs = 200

# Monad Testnet Configuration
eth-rpc-url="https://testnet-rpc.monad.xyz"
chain_id = 10143

# Use more recent solc version
solc = "0.8.26"

# Archive contains old Uniswap and AMM-related code
exclude_paths = ["archive"]